drop extension if exists "pg_net";

create sequence "public"."bom_id_seq";

create sequence "public"."product_packages_id_seq";

create sequence "public"."product_type_id_seq";

create sequence "public"."product_variant_link_id_seq";

create sequence "public"."storage_locations_id_seq";

create sequence "public"."untitled_table_256_id_seq";

create sequence "public"."untitled_table_258_id_seq";


  create table "public"."bom" (
    "id" integer not null default nextval('public.untitled_table_256_id_seq'::regclass),
    "parent" text,
    "child" text,
    "brand" text,
    "qty" integer
      );


alter table "public"."bom" enable row level security;


  create table "public"."product_attribute" (
    "attribute_id" text not null,
    "name" text not null,
    "value_id" text not null,
    "value_name" text not null
      );


alter table "public"."product_attribute" enable row level security;


  create table "public"."product_master" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "article_type" text,
    "name" text,
    "template_id" text,
    "internal_reference" text not null,
    "gtin" bigint,
    "sellable" boolean,
    "purchasable" boolean,
    "odoo_product_id" text default 'not imported'::text,
    "updated_at" timestamp with time zone,
    "prod_id" integer,
    "brand_cat" text,
    "package_id" text,
    "weight_net" real,
    "weight_gross" real,
    "length" integer,
    "width" integer,
    "height" integer,
    "temp_id" text
      );


alter table "public"."product_master" enable row level security;


  create table "public"."product_packages" (
    "id" integer not null default nextval('public.product_packages_id_seq'::regclass),
    "name" text,
    "type" text,
    "length" integer,
    "width" integer,
    "height" integer
      );



  create table "public"."product_template" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "template_id" text not null,
    "internal_reference" text not null,
    "name" text,
    "is_active" boolean
      );


alter table "public"."product_template" enable row level security;


  create table "public"."product_type" (
    "id" integer not null default nextval('public.product_type_id_seq'::regclass),
    "type" text not null,
    "start_value" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."product_type" enable row level security;


  create table "public"."product_variant_link" (
    "id" integer not null default nextval('public.product_variant_link_id_seq'::regclass),
    "prod_id" integer,
    "value_id" text
      );


alter table "public"."product_variant_link" enable row level security;


  create table "public"."stg_product_master" (
    "id" integer not null default nextval('public.untitled_table_258_id_seq'::regclass),
    "internal_reference" text,
    "package_id" text,
    "weight_net" real,
    "weight_gross" real,
    "length" integer,
    "width" integer,
    "height" integer,
    "temp_id" text,
    "name" text,
    "brand_cat" text,
    "sellable" boolean,
    "purchasable" boolean,
    "article_type" text,
    "gtin" bigint
      );



  create table "public"."storage_location" (
    "id" integer not null default nextval('public.storage_locations_id_seq'::regclass),
    "usage" character varying(255),
    "name" character varying(255),
    "barcode" character varying(255),
    "location_id" text,
    "storage_category_id" text,
    "active" boolean default true,
    "gang" character varying(10),
    "regal" integer,
    "ebene" integer,
    "platz" integer,
    "parent_location" text
      );


alter table "public"."storage_location" enable row level security;

alter sequence "public"."product_packages_id_seq" owned by "public"."product_packages"."id";

alter sequence "public"."product_type_id_seq" owned by "public"."product_type"."id";

alter sequence "public"."product_variant_link_id_seq" owned by "public"."product_variant_link"."id";

alter sequence "public"."storage_locations_id_seq" owned by "public"."storage_location"."id";

alter sequence "public"."untitled_table_256_id_seq" owned by "public"."bom"."id";

alter sequence "public"."untitled_table_258_id_seq" owned by "public"."stg_product_master"."id";

CREATE UNIQUE INDEX product_attributes_pkey ON public.product_attribute USING btree (value_id, value_name);

CREATE UNIQUE INDEX product_attributes_value_ids_key ON public.product_attribute USING btree (value_name);

CREATE UNIQUE INDEX product_master_internal_reference_key ON public.product_master USING btree (internal_reference);

CREATE UNIQUE INDEX product_master_pkey ON public.product_master USING btree (id, internal_reference);

CREATE UNIQUE INDEX product_packages_pkey ON public.product_packages USING btree (id);

CREATE UNIQUE INDEX product_template_internal_reference_key ON public.product_template USING btree (internal_reference);

CREATE UNIQUE INDEX product_template_pkey ON public.product_template USING btree (id, template_id, internal_reference);

CREATE UNIQUE INDEX product_template_template_id_key ON public.product_template USING btree (template_id);

CREATE UNIQUE INDEX product_type_pkey ON public.product_type USING btree (id, type, start_value);

CREATE UNIQUE INDEX product_type_start_value_key ON public.product_type USING btree (start_value);

CREATE UNIQUE INDEX product_type_type_key ON public.product_type USING btree (type);

CREATE UNIQUE INDEX product_variant_link_pkey ON public.product_variant_link USING btree (id);

CREATE UNIQUE INDEX storage_locations_gang_regal_ebene_platz_key ON public.storage_location USING btree (gang, regal, ebene, platz);

CREATE UNIQUE INDEX storage_locations_pkey ON public.storage_location USING btree (id);

CREATE UNIQUE INDEX untitled_table_256_pkey ON public.bom USING btree (id);

CREATE UNIQUE INDEX untitled_table_258_pkey ON public.stg_product_master USING btree (id);

alter table "public"."bom" add constraint "untitled_table_256_pkey" PRIMARY KEY using index "untitled_table_256_pkey";

alter table "public"."product_attribute" add constraint "product_attributes_pkey" PRIMARY KEY using index "product_attributes_pkey";

alter table "public"."product_master" add constraint "product_master_pkey" PRIMARY KEY using index "product_master_pkey";

alter table "public"."product_packages" add constraint "product_packages_pkey" PRIMARY KEY using index "product_packages_pkey";

alter table "public"."product_template" add constraint "product_template_pkey" PRIMARY KEY using index "product_template_pkey";

alter table "public"."product_type" add constraint "product_type_pkey" PRIMARY KEY using index "product_type_pkey";

alter table "public"."product_variant_link" add constraint "product_variant_link_pkey" PRIMARY KEY using index "product_variant_link_pkey";

alter table "public"."stg_product_master" add constraint "untitled_table_258_pkey" PRIMARY KEY using index "untitled_table_258_pkey";

alter table "public"."storage_location" add constraint "storage_locations_pkey" PRIMARY KEY using index "storage_locations_pkey";

alter table "public"."bom" add constraint "bom_child_fkey" FOREIGN KEY (child) REFERENCES public.product_master(internal_reference) not valid;

alter table "public"."bom" validate constraint "bom_child_fkey";

alter table "public"."bom" add constraint "bom_parent_fkey" FOREIGN KEY (parent) REFERENCES public.product_master(internal_reference) not valid;

alter table "public"."bom" validate constraint "bom_parent_fkey";

alter table "public"."product_attribute" add constraint "product_attributes_value_ids_key" UNIQUE using index "product_attributes_value_ids_key";

alter table "public"."product_master" add constraint "product_master_article_type_fkey" FOREIGN KEY (article_type) REFERENCES public.product_type(type) not valid;

alter table "public"."product_master" validate constraint "product_master_article_type_fkey";

alter table "public"."product_master" add constraint "product_master_internal_reference_key" UNIQUE using index "product_master_internal_reference_key";

alter table "public"."product_master" add constraint "product_master_template_id_fkey" FOREIGN KEY (template_id) REFERENCES public.product_template(template_id) not valid;

alter table "public"."product_master" validate constraint "product_master_template_id_fkey";

alter table "public"."product_template" add constraint "product_template_internal_reference_key" UNIQUE using index "product_template_internal_reference_key";

alter table "public"."product_template" add constraint "product_template_template_id_key" UNIQUE using index "product_template_template_id_key";

alter table "public"."product_type" add constraint "product_type_start_value_key" UNIQUE using index "product_type_start_value_key";

alter table "public"."product_type" add constraint "product_type_type_key" UNIQUE using index "product_type_type_key";

alter table "public"."storage_location" add constraint "storage_locations_gang_regal_ebene_platz_key" UNIQUE using index "storage_locations_gang_regal_ebene_platz_key";

set check_function_bodies = off;

create or replace view "public"."bom_explosion_view1" as  WITH RECURSIVE clean_bom AS (
         SELECT b.parent,
            b.child,
            b.qty,
            b.brand,
            pm_p.name AS parent_name,
            pm_p.gtin AS parent_gtin,
            pm_c.name AS child_name,
            pm_c.gtin AS child_gtin
           FROM ((public.bom b
             JOIN public.product_master pm_p ON ((pm_p.internal_reference = b.parent)))
             JOIN public.product_master pm_c ON ((pm_c.internal_reference = b.child)))
        ), bom_explosion AS (
         SELECT cb.parent AS root_ref,
            cb.child AS current_child,
            1 AS level,
            cb.qty AS qty_total,
            cb.brand,
            ARRAY[cb.parent, cb.child] AS path_refs,
            ARRAY[cb.parent_name, cb.child_name] AS path_names_pure,
            ARRAY[cb.parent_gtin, cb.child_gtin] AS path_gtins,
            ARRAY[cb.qty] AS path_qtys
           FROM clean_bom cb
          WHERE (NOT (EXISTS ( SELECT 1
                   FROM clean_bom x
                  WHERE (x.child = cb.parent))))
        UNION ALL
         SELECT be_1.root_ref,
            cb.child,
            (be_1.level + 1),
            (be_1.qty_total * cb.qty),
            be_1.brand,
            (be_1.path_refs || cb.child),
            (be_1.path_names_pure || cb.child_name),
            (be_1.path_gtins || cb.child_gtin),
            (be_1.path_qtys || cb.qty)
           FROM (clean_bom cb
             JOIN bom_explosion be_1 ON ((cb.parent = be_1.current_child)))
          WHERE (NOT (cb.child = ANY (be_1.path_refs)))
        )
 SELECT root_ref,
    brand,
    level AS depth,
    qty_total,
    ((path_refs[1] || ' - '::text) || path_names_pure[1]) AS root_info,
    ((path_refs[2] || ' - '::text) || path_names_pure[2]) AS level_1_info,
    path_gtins[2] AS level_1_gtin,
    path_qtys[1] AS level_1_qty,
        CASE
            WHEN ((level = 2) AND (path_names_pure[3] IS NOT NULL) AND (path_names_pure[3] !~~* '%polybag%'::text) AND (path_names_pure[2] !~~* '%polybag%'::text)) THEN ((path_refs[3] || ' - Polybag '::text) || path_names_pure[3])
            ELSE ((path_refs[3] || ' - '::text) || path_names_pure[3])
        END AS level_2_info,
    path_gtins[3] AS level_2_gtin,
    path_qtys[2] AS level_2_qty,
        CASE
            WHEN ((level = 3) AND (path_names_pure[4] IS NOT NULL) AND (path_names_pure[4] !~~* '%polybag%'::text) AND (path_names_pure[3] !~~* '%polybag%'::text)) THEN ((path_refs[4] || ' - Polybag '::text) || path_names_pure[4])
            ELSE ((path_refs[4] || ' - '::text) || path_names_pure[4])
        END AS level_3_info,
    path_gtins[4] AS level_3_gtin,
    path_qtys[3] AS level_3_qty,
        CASE
            WHEN ((level = 4) AND (path_names_pure[5] IS NOT NULL) AND (path_names_pure[5] !~~* '%polybag%'::text) AND (path_names_pure[4] !~~* '%polybag%'::text)) THEN ((path_refs[5] || ' - Polybag '::text) || path_names_pure[5])
            ELSE ((path_refs[5] || ' - '::text) || path_names_pure[5])
        END AS level_4_info,
    path_gtins[5] AS level_4_gtin,
    path_qtys[4] AS level_4_qty
   FROM bom_explosion be
  WHERE (NOT (EXISTS ( SELECT 1
           FROM clean_bom x
          WHERE (x.parent = be.current_child))))
  ORDER BY root_ref, path_refs;


create or replace view "public"."bom_view" as  WITH RECURSIVE clean_bom AS (
         SELECT b.parent,
            b.child,
            b.qty,
            b.brand,
            pm_p.name AS parent_name,
            pm_p.gtin AS parent_gtin,
            pm_c.name AS child_name,
            pm_c.gtin AS child_gtin
           FROM ((public.bom b
             JOIN public.product_master pm_p ON ((pm_p.internal_reference = b.parent)))
             JOIN public.product_master pm_c ON ((pm_c.internal_reference = b.child)))
        ), bom_explosion AS (
         SELECT cb.parent AS root_ref,
            cb.child AS current_child,
            1 AS level,
            cb.qty AS qty_total,
            cb.brand,
            ARRAY[cb.parent, cb.child] AS path_refs,
            ARRAY[cb.parent_name, cb.child_name] AS path_names_pure,
            ARRAY[cb.parent_gtin, cb.child_gtin] AS path_gtins,
            ARRAY[cb.qty] AS path_qtys
           FROM clean_bom cb
          WHERE (NOT (EXISTS ( SELECT 1
                   FROM clean_bom x
                  WHERE (x.child = cb.parent))))
        UNION ALL
         SELECT be_1.root_ref,
            cb.child,
            (be_1.level + 1),
            (be_1.qty_total * cb.qty),
            be_1.brand,
            (be_1.path_refs || cb.child),
            (be_1.path_names_pure || cb.child_name),
            (be_1.path_gtins || cb.child_gtin),
            (be_1.path_qtys || cb.qty)
           FROM (clean_bom cb
             JOIN bom_explosion be_1 ON ((cb.parent = be_1.current_child)))
          WHERE (NOT (cb.child = ANY (be_1.path_refs)))
        )
 SELECT brand,
    level AS depth,
    qty_total,
    path_refs[1] AS root_ref,
    path_names_pure[1] AS root_name,
    path_gtins[1] AS root_gtin,
    path_refs[2] AS level_1_ref,
    path_names_pure[2] AS level_1_name,
    path_gtins[2] AS level_1_gtin,
    path_qtys[1] AS level_1_qty,
    path_refs[3] AS level_2_ref,
    path_names_pure[3] AS level_2_name,
    path_gtins[3] AS level_2_gtin,
    path_qtys[2] AS level_2_qty,
    path_refs[4] AS level_3_ref,
    path_names_pure[4] AS level_3_name,
    path_gtins[4] AS level_3_gtin,
    path_qtys[3] AS level_3_qty,
    path_refs[5] AS level_4_ref,
    path_names_pure[5] AS level_4_name,
    path_gtins[5] AS level_4_gtin,
    path_qtys[4] AS level_4_qty
   FROM bom_explosion be
  WHERE (NOT (EXISTS ( SELECT 1
           FROM clean_bom x
          WHERE (x.parent = be.current_child))))
  ORDER BY path_refs[1], path_refs;


CREATE OR REPLACE FUNCTION public.fn_calculate_gtin_check_digit(p_gtin12 text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_sum INT := 0;
    v_digit INT;
    v_check_digit INT;
BEGIN
    -- Gewichtung: 1, 3, 1, 3... von rechts nach links
    FOR i IN 1..12 LOOP
        v_digit := CAST(SUBSTRING(p_gtin12 FROM i FOR 1) AS INT);
        IF i % 2 = 0 THEN
            v_sum := v_sum + (v_digit * 3);
        ELSE
            v_sum := v_sum + v_digit;
        END IF;
    END LOOP;
    
    v_check_digit := (10 - (v_sum % 10)) % 10;
    RETURN p_gtin12 || v_check_digit::text;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.fn_manage_product_ids()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_start_val BIGINT;
    v_new_ref BIGINT;
    v_base_gtin TEXT;
    v_check_digit INT;
BEGIN
    -- 1. Lock gegen Race-Conditions bei Nummernvergabe
    PERFORM pg_advisory_xact_lock(hashtext(NEW.article_type::text));

    -- 2. LOGIK FÜR INTERNAL_REFERENCE (Artikelnummer)
    IF NEW.internal_reference IS NULL THEN
        -- Validierung der Pflichtfelder (korrigiert auf Spalte "name")
        IF NEW.name IS NULL OR NEW.article_type IS NULL OR NEW.sellable IS NULL THEN
            RAISE EXCEPTION 'Neuimport fehlgeschlagen: Name, Typ und Sellable müssen ausgefüllt sein!';
        END IF;

        -- Startwert aus der Tabelle "product_type" (Spalte "type") holen
        SELECT start_value INTO v_start_val 
        FROM product_type 
        WHERE type = NEW.article_type;
        
        IF v_start_val IS NOT NULL THEN
            -- Suche nach der nächsten freien Nummer (Gap-Filling Logik)
            SELECT COALESCE(
                (SELECT v_start_val WHERE NOT EXISTS (
                    SELECT 1 FROM product_master WHERE internal_reference = v_start_val::text
                )),
                (SELECT MIN(CAST(NULLIF(internal_reference, '') AS BIGINT) + 1)
                 FROM product_master
                 WHERE article_type = NEW.article_type
                   AND internal_reference ~ '^[0-9]+$' 
                   AND CAST(internal_reference AS BIGINT) >= v_start_val
                   AND NOT EXISTS (
                     SELECT 1 FROM product_master p2 
                     WHERE p2.internal_reference = (CAST(NULLIF(product_master.internal_reference, '') AS BIGINT) + 1)::text
                   ))
            ) INTO v_new_ref;

            NEW.internal_reference := v_new_ref::text;
        END IF;
    END IF;

    -- 3. LOGIK FÜR GTIN GENERIERUNG
    IF NEW.sellable = true AND NEW.gtin IS NULL THEN
        -- Fix: gtin::TEXT casten, um SUBSTRING nutzen zu können
        SELECT MAX(SUBSTRING(gtin::TEXT FROM 1 FOR 12)::BIGINT) INTO v_base_gtin
        FROM product_master
        WHERE gtin::TEXT ~ '^[0-9]{13}$';

        IF v_base_gtin IS NULL THEN
            v_base_gtin := '426000000001'; 
        ELSE
            v_base_gtin := (v_base_gtin::BIGINT + 1)::TEXT;
        END IF;

        -- Prüfziffer berechnen und GTIN zusammensetzen
        v_check_digit := public.gs1_check_digit(v_base_gtin);
        
        -- Zurück zu BIGINT casten für die Zieltabelle
        NEW.gtin := (v_base_gtin || v_check_digit::TEXT)::BIGINT;
    END IF;

    -- Zeitstempel setzen
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.gs1_check_digit(gtin12 text)
 RETURNS integer
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
  sum INT := 0;
  digit INT;
BEGIN
  -- Sicherheitscheck
  IF gtin12 !~ '^[0-9]{12}$' THEN
    RAISE EXCEPTION 'Ungültige GTIN-12: %', gtin12;
  END IF;

  -- GS1-Prüfzifferberechnung
  FOR i IN 1..12 LOOP
    digit := SUBSTRING(gtin12 FROM (13 - i) FOR 1)::INT;
    IF i % 2 = 1 THEN
      sum := sum + digit * 3;
    ELSE
      sum := sum + digit;
    END IF;
  END LOOP;

  RETURN (10 - (sum % 10)) % 10;
END;
$function$
;

create or replace view "public"."odoo_variant_reimport" as  WITH attribute_summary AS (
         SELECT pva.prod_id,
            string_agg(pat.value_name, ','::text ORDER BY pat.attribute_id) AS all_attributes,
            string_agg(pva.value_id, ','::text ORDER BY pat.attribute_id) AS all_attributes_id
           FROM (public.product_variant_link pva
             JOIN public.product_attribute pat ON ((pva.value_id = pat.value_id)))
          GROUP BY pva.prod_id
        )
 SELECT pm.internal_reference AS variant_reference,
    pm.template_id,
    pt.internal_reference AS template_reference,
    COALESCE(asum.all_attributes, 'Keine Attribute'::text) AS attributes,
    asum.all_attributes_id
   FROM ((public.product_master pm
     LEFT JOIN attribute_summary asum ON ((pm.prod_id = asum.prod_id)))
     LEFT JOIN public.product_template pt ON ((pm.template_id = pt.template_id)))
  WHERE (pm.template_id IS NOT NULL);


CREATE OR REPLACE PROCEDURE public.pr_migrate_staging_to_master()
 LANGUAGE plpgsql
AS $procedure$
DECLARE
    rows_affected INT;
BEGIN
    -- Der eigentliche Import-Befehl
    INSERT INTO product_master (
        article_type, 
        product_name, 
        internal_reference, 
        gtin_13, 
        sellable
    )
    SELECT 
        INITCAP(LOWER(COALESCE(s.article_type, p.article_type))),
        COALESCE(s.product_name, p.product_name),
        s.internal_reference, 
        s.gtin_13, 
        COALESCE(s.sellable, p.sellable)
    FROM stg_product_master s
    LEFT JOIN product_master p ON s.internal_reference = p.internal_reference
    WHERE 
        -- Validierung: Bestand existiert ODER Neuimport ist vollständig
        (p.internal_reference IS NOT NULL) OR 
        (s.article_type IS NOT NULL AND s.product_name IS NOT NULL AND s.sellable IS NOT NULL)
    ON CONFLICT (internal_reference) 
    DO UPDATE SET 
        gtin_13 = EXCLUDED.gtin_13,
        sellable = COALESCE(EXCLUDED.sellable, product_master.sellable),
        product_name = COALESCE(EXCLUDED.product_name, product_master.product_name),
        updated_at = CURRENT_TIMESTAMP;

    -- Info ausgeben, wie viele Zeilen verarbeitet wurden
    GET DIAGNOSTICS rows_affected = ROW_COUNT;
    RAISE NOTICE 'Migration abgeschlossen: % Zeilen verarbeitet.', rows_affected;
END;
$procedure$
;

CREATE OR REPLACE FUNCTION public.split_storage_location_name()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Regex-Erklärung: 
    -- ^           = Start des Textes
    -- [^-]+       = Mindestens ein Zeichen, das kein Bindestrich ist
    -- -           = Ein Bindestrich
    -- {3}         = Das Ganze (Zeichen + Bindestrich) exakt dreimal
    -- [^-]+       = Ein letztes Segment ohne Bindestrich
    -- $           = Ende des Textes
    
    IF NEW.name ~ '^[^-]+-[^-]+-[^-]+-[^-]+$' THEN
        NEW.gang  := split_part(NEW.name, '-', 1);
        NEW.regal := split_part(NEW.name, '-', 2);
        NEW.ebene := split_part(NEW.name, '-', 3);
        NEW.platz := split_part(NEW.name, '-', 4);
    ELSE
        -- Falls das Muster nicht exakt 4 Teile hat:
        NEW.gang  := NULL;
        NEW.regal := NULL;
        NEW.ebene := NULL;
        NEW.platz := NULL;
    END IF;
    
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_modified_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_timestamp_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$
;

grant delete on table "public"."bom" to "anon";

grant insert on table "public"."bom" to "anon";

grant references on table "public"."bom" to "anon";

grant select on table "public"."bom" to "anon";

grant trigger on table "public"."bom" to "anon";

grant truncate on table "public"."bom" to "anon";

grant update on table "public"."bom" to "anon";

grant delete on table "public"."bom" to "authenticated";

grant insert on table "public"."bom" to "authenticated";

grant references on table "public"."bom" to "authenticated";

grant select on table "public"."bom" to "authenticated";

grant trigger on table "public"."bom" to "authenticated";

grant truncate on table "public"."bom" to "authenticated";

grant update on table "public"."bom" to "authenticated";

grant delete on table "public"."bom" to "service_role";

grant insert on table "public"."bom" to "service_role";

grant references on table "public"."bom" to "service_role";

grant select on table "public"."bom" to "service_role";

grant trigger on table "public"."bom" to "service_role";

grant truncate on table "public"."bom" to "service_role";

grant update on table "public"."bom" to "service_role";

grant delete on table "public"."product_attribute" to "anon";

grant insert on table "public"."product_attribute" to "anon";

grant references on table "public"."product_attribute" to "anon";

grant select on table "public"."product_attribute" to "anon";

grant trigger on table "public"."product_attribute" to "anon";

grant truncate on table "public"."product_attribute" to "anon";

grant update on table "public"."product_attribute" to "anon";

grant delete on table "public"."product_attribute" to "authenticated";

grant insert on table "public"."product_attribute" to "authenticated";

grant references on table "public"."product_attribute" to "authenticated";

grant select on table "public"."product_attribute" to "authenticated";

grant trigger on table "public"."product_attribute" to "authenticated";

grant truncate on table "public"."product_attribute" to "authenticated";

grant update on table "public"."product_attribute" to "authenticated";

grant delete on table "public"."product_attribute" to "service_role";

grant insert on table "public"."product_attribute" to "service_role";

grant references on table "public"."product_attribute" to "service_role";

grant select on table "public"."product_attribute" to "service_role";

grant trigger on table "public"."product_attribute" to "service_role";

grant truncate on table "public"."product_attribute" to "service_role";

grant update on table "public"."product_attribute" to "service_role";

grant delete on table "public"."product_master" to "anon";

grant insert on table "public"."product_master" to "anon";

grant references on table "public"."product_master" to "anon";

grant select on table "public"."product_master" to "anon";

grant trigger on table "public"."product_master" to "anon";

grant truncate on table "public"."product_master" to "anon";

grant update on table "public"."product_master" to "anon";

grant delete on table "public"."product_master" to "authenticated";

grant insert on table "public"."product_master" to "authenticated";

grant references on table "public"."product_master" to "authenticated";

grant select on table "public"."product_master" to "authenticated";

grant trigger on table "public"."product_master" to "authenticated";

grant truncate on table "public"."product_master" to "authenticated";

grant update on table "public"."product_master" to "authenticated";

grant delete on table "public"."product_master" to "service_role";

grant insert on table "public"."product_master" to "service_role";

grant references on table "public"."product_master" to "service_role";

grant select on table "public"."product_master" to "service_role";

grant trigger on table "public"."product_master" to "service_role";

grant truncate on table "public"."product_master" to "service_role";

grant update on table "public"."product_master" to "service_role";

grant delete on table "public"."product_packages" to "anon";

grant insert on table "public"."product_packages" to "anon";

grant references on table "public"."product_packages" to "anon";

grant select on table "public"."product_packages" to "anon";

grant trigger on table "public"."product_packages" to "anon";

grant truncate on table "public"."product_packages" to "anon";

grant update on table "public"."product_packages" to "anon";

grant delete on table "public"."product_packages" to "authenticated";

grant insert on table "public"."product_packages" to "authenticated";

grant references on table "public"."product_packages" to "authenticated";

grant select on table "public"."product_packages" to "authenticated";

grant trigger on table "public"."product_packages" to "authenticated";

grant truncate on table "public"."product_packages" to "authenticated";

grant update on table "public"."product_packages" to "authenticated";

grant delete on table "public"."product_packages" to "service_role";

grant insert on table "public"."product_packages" to "service_role";

grant references on table "public"."product_packages" to "service_role";

grant select on table "public"."product_packages" to "service_role";

grant trigger on table "public"."product_packages" to "service_role";

grant truncate on table "public"."product_packages" to "service_role";

grant update on table "public"."product_packages" to "service_role";

grant delete on table "public"."product_template" to "anon";

grant insert on table "public"."product_template" to "anon";

grant references on table "public"."product_template" to "anon";

grant select on table "public"."product_template" to "anon";

grant trigger on table "public"."product_template" to "anon";

grant truncate on table "public"."product_template" to "anon";

grant update on table "public"."product_template" to "anon";

grant delete on table "public"."product_template" to "authenticated";

grant insert on table "public"."product_template" to "authenticated";

grant references on table "public"."product_template" to "authenticated";

grant select on table "public"."product_template" to "authenticated";

grant trigger on table "public"."product_template" to "authenticated";

grant truncate on table "public"."product_template" to "authenticated";

grant update on table "public"."product_template" to "authenticated";

grant delete on table "public"."product_template" to "service_role";

grant insert on table "public"."product_template" to "service_role";

grant references on table "public"."product_template" to "service_role";

grant select on table "public"."product_template" to "service_role";

grant trigger on table "public"."product_template" to "service_role";

grant truncate on table "public"."product_template" to "service_role";

grant update on table "public"."product_template" to "service_role";

grant delete on table "public"."product_type" to "anon";

grant insert on table "public"."product_type" to "anon";

grant references on table "public"."product_type" to "anon";

grant select on table "public"."product_type" to "anon";

grant trigger on table "public"."product_type" to "anon";

grant truncate on table "public"."product_type" to "anon";

grant update on table "public"."product_type" to "anon";

grant delete on table "public"."product_type" to "authenticated";

grant insert on table "public"."product_type" to "authenticated";

grant references on table "public"."product_type" to "authenticated";

grant select on table "public"."product_type" to "authenticated";

grant trigger on table "public"."product_type" to "authenticated";

grant truncate on table "public"."product_type" to "authenticated";

grant update on table "public"."product_type" to "authenticated";

grant delete on table "public"."product_type" to "service_role";

grant insert on table "public"."product_type" to "service_role";

grant references on table "public"."product_type" to "service_role";

grant select on table "public"."product_type" to "service_role";

grant trigger on table "public"."product_type" to "service_role";

grant truncate on table "public"."product_type" to "service_role";

grant update on table "public"."product_type" to "service_role";

grant delete on table "public"."product_variant_link" to "anon";

grant insert on table "public"."product_variant_link" to "anon";

grant references on table "public"."product_variant_link" to "anon";

grant select on table "public"."product_variant_link" to "anon";

grant trigger on table "public"."product_variant_link" to "anon";

grant truncate on table "public"."product_variant_link" to "anon";

grant update on table "public"."product_variant_link" to "anon";

grant delete on table "public"."product_variant_link" to "authenticated";

grant insert on table "public"."product_variant_link" to "authenticated";

grant references on table "public"."product_variant_link" to "authenticated";

grant select on table "public"."product_variant_link" to "authenticated";

grant trigger on table "public"."product_variant_link" to "authenticated";

grant truncate on table "public"."product_variant_link" to "authenticated";

grant update on table "public"."product_variant_link" to "authenticated";

grant delete on table "public"."product_variant_link" to "service_role";

grant insert on table "public"."product_variant_link" to "service_role";

grant references on table "public"."product_variant_link" to "service_role";

grant select on table "public"."product_variant_link" to "service_role";

grant trigger on table "public"."product_variant_link" to "service_role";

grant truncate on table "public"."product_variant_link" to "service_role";

grant update on table "public"."product_variant_link" to "service_role";

grant delete on table "public"."stg_product_master" to "anon";

grant insert on table "public"."stg_product_master" to "anon";

grant references on table "public"."stg_product_master" to "anon";

grant select on table "public"."stg_product_master" to "anon";

grant trigger on table "public"."stg_product_master" to "anon";

grant truncate on table "public"."stg_product_master" to "anon";

grant update on table "public"."stg_product_master" to "anon";

grant delete on table "public"."stg_product_master" to "authenticated";

grant insert on table "public"."stg_product_master" to "authenticated";

grant references on table "public"."stg_product_master" to "authenticated";

grant select on table "public"."stg_product_master" to "authenticated";

grant trigger on table "public"."stg_product_master" to "authenticated";

grant truncate on table "public"."stg_product_master" to "authenticated";

grant update on table "public"."stg_product_master" to "authenticated";

grant delete on table "public"."stg_product_master" to "service_role";

grant insert on table "public"."stg_product_master" to "service_role";

grant references on table "public"."stg_product_master" to "service_role";

grant select on table "public"."stg_product_master" to "service_role";

grant trigger on table "public"."stg_product_master" to "service_role";

grant truncate on table "public"."stg_product_master" to "service_role";

grant update on table "public"."stg_product_master" to "service_role";

grant delete on table "public"."storage_location" to "anon";

grant insert on table "public"."storage_location" to "anon";

grant references on table "public"."storage_location" to "anon";

grant select on table "public"."storage_location" to "anon";

grant trigger on table "public"."storage_location" to "anon";

grant truncate on table "public"."storage_location" to "anon";

grant update on table "public"."storage_location" to "anon";

grant delete on table "public"."storage_location" to "authenticated";

grant insert on table "public"."storage_location" to "authenticated";

grant references on table "public"."storage_location" to "authenticated";

grant select on table "public"."storage_location" to "authenticated";

grant trigger on table "public"."storage_location" to "authenticated";

grant truncate on table "public"."storage_location" to "authenticated";

grant update on table "public"."storage_location" to "authenticated";

grant delete on table "public"."storage_location" to "service_role";

grant insert on table "public"."storage_location" to "service_role";

grant references on table "public"."storage_location" to "service_role";

grant select on table "public"."storage_location" to "service_role";

grant trigger on table "public"."storage_location" to "service_role";

grant truncate on table "public"."storage_location" to "service_role";

grant update on table "public"."storage_location" to "service_role";

CREATE TRIGGER set_timestamp BEFORE UPDATE ON public.product_master FOR EACH ROW EXECUTE FUNCTION public.update_modified_column();

CREATE TRIGGER trg_manage_ids BEFORE INSERT ON public.product_master FOR EACH ROW EXECUTE FUNCTION public.fn_manage_product_ids();

CREATE TRIGGER trg_manage_ids_update BEFORE UPDATE ON public.product_master FOR EACH ROW EXECUTE FUNCTION public.fn_manage_product_ids();

CREATE TRIGGER trg_manage_product_ids BEFORE INSERT ON public.product_master FOR EACH ROW EXECUTE FUNCTION public.fn_manage_product_ids();

CREATE TRIGGER trg_manage_product_ids_update BEFORE UPDATE ON public.product_master FOR EACH ROW EXECUTE FUNCTION public.fn_manage_product_ids();

CREATE TRIGGER trg_split_storage_location BEFORE INSERT OR UPDATE OF name ON public.storage_location FOR EACH ROW EXECUTE FUNCTION public.split_storage_location_name();


