-- BOM-Session: Kopf je Lieferant/Projekt
create table public.bom_session (
    id              serial primary key,
    bezeichnung     text        not null,
    lieferant       text,
    status          text        not null default 'draft'
                    check (status in ('draft','review','freigegeben','archiviert')),
    erstellt_von    text,
    erstellt_am     timestamptz not null default now(),
    freigegeben_am  timestamptz
);

-- Versionen je Session
create table public.bom_version (
    id          serial primary key,
    session_id  int  not null references bom_session(id) on delete cascade,
    version_nr  int  not null default 1,
    kommentar   text,
    erstellt_am timestamptz not null default now(),
    unique (session_id, version_nr)
);

create index idx_bom_version_session on bom_version(session_id);

-- Staging-Artikel: identische Spalten wie product_master + staging-felder
drop table if exists public.stg_product_master;

create table public.staging_artikel (
    id                  bigint generated by default as identity primary key,
    created_at          timestamptz not null default now(),
    article_type        text references product_type(type),
    name                text,
    template_id         text,
    internal_reference  text unique,
    gtin                bigint,
    sellable            boolean,
    purchasable         boolean,
    odoo_product_id     text,
    prod_id             int,
    brand_cat           text,
    package_id          text,
    weight_net          real,
    weight_gross        real,
    length              int,
    width               int,
    height              int,
    temp_id             text,
    -- Staging-spezifische Felder
    version_id          int references bom_version(id) on delete cascade,
    temp_ref            text not null,
    match_status        text not null default 'offen'
                        check (match_status in
                          ('offen','matched','neu_anlegen','ignorieren')),
    matched_ref         text references product_master(internal_reference),
    fuzzy_hits          jsonb,
    unique (version_id, temp_ref)
);

create index idx_staging_artikel_version on staging_artikel(version_id);
create index idx_staging_artikel_status  on staging_artikel(match_status);

-- Staging-BOM: identische Spalten wie bom + staging-felder
create table public.staging_bom (
    id               int generated by default as identity primary key,
    parent           text,
    child            text,
    brand            text,
    qty              int,
    -- Staging-spezifische Felder
    version_id       int references bom_version(id) on delete cascade,
    parent_temp_ref  text,
    child_temp_ref   text not null,
    parent_ref       text references product_master(internal_reference),
    child_ref        text references product_master(internal_reference)
);

create index idx_staging_bom_version on staging_bom(version_id);